env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-essential
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - vue
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
