/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminBooking: typeof import('./Admin/AdminBooking.vue')['default']
    DashboardAdmin: typeof import('./Admin/DashboardAdmin.vue')['default']
    InvoicePrint: typeof import('./Admin/InvoicePrint.vue')['default']
    LoginUsers: typeof import('./LoginUsers.vue')['default']
    PaymentList: typeof import('./Admin/PaymentList.vue')['default']
    RoombookEdit: typeof import('./Admin/RoombookEdit.vue')['default']
    RoombookList: typeof import('./Admin/RoombookList.vue')['default']
    RoomShow: typeof import('./Admin/RoomShow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaffShow: typeof import('./Admin/StaffShow.vue')['default']
    UserBooking: typeof import('./UserBooking.vue')['default']
  }
}
