name: PHPUnit Test 
on:
  push:
    branches: ['upstream', 'origin']
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['8.3']
        laravel: ['13.*']
        dependency-version: [prefer-stable]
        include:
          - laravel: '13.*'
            testbench: '11.5.50'
            phpunit: '11.5.0'
            experimental: false

    name: ${{ matrix.os }} - PHP ${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Copy environment file
        run: cp .env.testing .env || cp .env.example .env

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --with-all-dependencies

      - name: Create SQLite Database
        run: |
          mkdir -p database
          sqlite3 database/database.sqlite

      - name: Execute Artisan Commands
        run: |
          cp .env.testing .env
          php artisan key:generate

      - name: Run Unit Tests
        run: php artisan test
